### PR TITLE
Fix for Capybara 2.7; Rack driver now considers hidden fields invisible

### PR DESCRIPTION
**Pull request by lawso017**
Fresh bundle install included Capybara 2.7; form_builder specs failed because latest Capybara Rack driver does not find hidden fields by default.

### CODE REVIEW

**Comment by lawso017** [comment]
Also replaced fog with fog/aws, and replaced uuidtools with SecureRandom.uuid to reduce dependencies.

**Comment by lawso017** [comment]
FYI, reducing the dependency footprint fog -> fog/aws dropped slug footprint by ~20MB on heroku.

**Comment by dwilkie** [comment]
Thanks for the PR! Looks like nobody is maintaining this gem anymore. Are you interested in maintaining it? Reply here and i'll give your access.
Cheers

**Comment by p8** [comment]
@dwilkie I hope to have some time next week to look at some pull requests, including this one.

**Comment by lawso017** [comment]
@p8 @dwilkie I am happy to help out; really appreciate this gem and rely on it in several projects.

**Pull request merged**
