### PR TITLE
Update policies & signature sto use Aws sig v4 (AWS4-HMAC-SHA256)

### LINKED ISSUE #183: Please use AWS4-HMAC-SHA256
when upload  to new regin, receive message :The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256. def signature
      Base64.encode64(
        OpenSSL::HMAC.digest(
          OpenSSL::Digest.new('sha1'),
          aws_secret_access_key, policy
        )
      ).gsub("\n","")
sha1 no supported to new regin,how to update use sha256.?????????????????

### PR DESCRIPTION
**Pull request by fran-worley**
fixes #183

Based on http://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-UsingHTTPPOST.html
and https://github.com/RobotsAndPencils/s3_direct_upload

### CODE REVIEW

**Comment by sunny** [comment]
\o/ This would be really great to have on master.

**Comment by MelnikVasya** [comment]
+1

**Comment by lawso017** [comment]
@fran-worley @p8 after accepting this PR into master, I ended up reverting it; in my application I was receiving SignatureDoesNotMatch errors with uploads after the v4 change.

I have the changes on a branch in my repo and will keep playing with them as I have time but did not want to leave master in a state where previously-working users would break.

Any thoughts on where a signature error could come from with a previously working upload configuration are appreciated. It may be that my implementation needs to be tweaked but my initial review of the code seemed like the v4 change would be backwards compatible.

**Comment by p8** [comment]
@fran-worley @lawso017 I'm not seeing it either. Not much has changed: https://github.com/SafetyToolbox/carrierwave_direct/compare/aws-sig-v4...dwilkie:413aac6 . The only thing might be my enforce_utf8 option. I'll try to get things working locally.

A new build would be nice.

**Comment by p8** [comment]
@lawso017 I've commited the following which fixes two deprecated methods.
https://github.com/dwilkie/carrierwave_direct/commit/4f857a8e4368d7efda9f751c0de872993e3354a3
This probably caused this PR to fail.

**Comment by p8** [comment]
This PR works fine for me now.
I've merged it back into master https://github.com/dwilkie/carrierwave_direct/commit/328ed7d4c15a76e04770ead17a4964c7f8385713

**Comment by lawso017** [comment]
Excellent @p8 -- and the problem was on my end; I wasn't using the form and had forgotten to update the post request to use the new values provided by the library. Will add a note to the readme.

**Pull request merged**
